name: Deploy Local
on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted  # <-- importante, dice que use tu PC
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./mvnw clean package -DskipTests
#      - name: Deploy
#        run: docker compose up -d --build