name: Deploy Linux
on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted  # <-- importante, dice que use tu PC
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: mvn clean package -DskipTests
      - name: Create Image
        run: docker build -t api-github-actions:latest .
      - name: Delete container
        run: docker rm -f api-actions || true
      - name: Deploy
        run: docker run --name api-actions -p 8085:8080 -d --restart always api-github-actions:latest