name: Deploy Local
on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted  # <-- importante, dice que use tu PC
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: mvn clean package -DskipTests
      - name: Create Image
        run: docker build -t api-github-actions:latest .
      - name: Delete container
        run: | 
          docker stop api-actions
          docker rm api-actions
      - name: Deploy
        run: docker run --name api-actions -p 8085:8080 -d api-github-actions:latest